---
title: "DEX Comparison Report"
author: Sascha Holzhauer
output:
    pdf_document:
        toc: true
        toc_depth: 2
        number_sections: true
        fig_width: 7
        fig_height: 4
        fig_caption: true
        df_print: kable
---

```{r, eval=TRUE, include = FALSE}
setwd(paste(dexpa$dirs$scripts, sep="/"))
```

# Parameters
## Product Information (`r input_db_runID(dp1)`)
```{r, eval=TRUE, results="asis", message=FALSE, error=FALSE, warning=FALSE, echo=FALSE}
invisible(futile.logger::flog.threshold(futile.logger::ERROR, name='dexr'))
dexR::output_table_param_products(dexpa)
invisible(futile.logger::flog.threshold(futile.logger::INFO, name='dexr'))
```
## Product Information (`r input_db_runID(dp2)`)
```{r, eval=TRUE, results="asis", message=FALSE, error=FALSE, warning=FALSE, echo=FALSE}
invisible(futile.logger::flog.threshold(futile.logger::ERROR, name='dexr'))
dexR::output_table_param_products(dp2)
invisible(futile.logger::flog.threshold(futile.logger::INFO, name='dexr'))
```
## Market Information (`r input_db_runID(dp1)`)
```{r, eval=TRUE, results="asis", message=FALSE, error=FALSE, warning=FALSE, echo=FALSE}
invisible(futile.logger::flog.threshold(futile.logger::ERROR, name='dexr'))
dexR::output_table_param_marketinfo(dp1)
invisible(futile.logger::flog.threshold(futile.logger::INFO, name='dexr'))
```
## Market Information (`r input_db_runID(dp2)`)
```{r, eval=TRUE, results="asis", message=FALSE, error=FALSE, warning=FALSE, echo=FALSE}
invisible(futile.logger::flog.threshold(futile.logger::ERROR, name='dexr'))
dexR::output_table_param_marketinfo(dp2)
invisible(futile.logger::flog.threshold(futile.logger::INFO, name='dexr'))
```

# Time Series
## Clearing Information

```{r, eval=TRUE, results="hide", echo=FALSE, messages=FALSE, warning=FALSE}
dexR::hl_figure_clearing_comp_numConsideredRequests(list(dp1, dp2))
```

## Price Statistics
```{r, eval=TRUE, results="hide", echo=FALSE, messages=FALSE, warning=FALSE}
dexpa$fig$height <- 550
dexR::hl_figure_clearing_comp_clearingPriceByCTbyProduct(list(dp1, dp2))
```

## Request Statistics
```{r, eval=TRUE, results="hide", echo=FALSE, messages=FALSE, warning=FALSE}
dexpa$fig$height <- 550
dexR::hl_figure_requests_numRequests_comp_byStatusBySubmT(list(dp1, dp2))
dexR::hl_figure_requests_numRequests_comp_byStatusByStartT(list(dp1, dp2))
```

